framework:
    http_client:
        scoped_clients:
            # only requests matching scope will use these options
            yousign.client:
                base_uri: 'https://api-sandbox.yousign.app/v3/'
                headers:
                    Accept: 'application/json'
                    Authorization: 'Bearer %env(YOUSIGN_SANDBOX_API_KEY)%'